### ISSUE TITLE
Module not found error

### ISSUE THREAD

**Issue by MaximMoinat** [hgrif/example-project#1]
Somehow when running this, the package cannot be found. I cloned your repo and gone through the setup instructions. Any ideas what could cause this?

The error:
```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-2-f01472c6d600> in <module>()
----> 1 import exampleproject as ep
      2 
      3 get_ipython().magic('matplotlib inline')

ModuleNotFoundError: No module named 'exampleproject'
```
I am running it on OSX High Sierra 10.13 and Python 3.6.

Btw: your blog post was a great read!

**Comment by hgrif** [comment]
Thanks!

This probably has to do either (i) with a dependency missing in the `environment.yml` or (ii) with the Python interpreter you've installed the package with versus the Python interpreter you're running when import `exampleproject`.

I'll assume you've created the conda virtual environment `example_project`with `conda env create -f environment.yml` and installed it in there.

Assuming you're using Jupyter Notebook:

- Try installing `ipykernel` with `conda install ipykernel`.
- Check that you're using the right kernel by going to `Kernel` -> `Change kernel` -> `Python: [conda env:example_project]`.
- Check if you can import now.

I've added `ipykernel` to the `environment.yml`, so I hope this solves the problem in the future.

Let me know if this fixes it for you!

**Comment by MaximMoinat** [comment]
Thanks for the pointers. I solved it in the end by updating jupyter notebook itself and installing nb_conda with `conda update jupyter_core jupyter_client & conda install nb_conda`. Turned out that I was still running an older version of jupyter (4.1).
